# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.1

#######################
# Optional info section
#######################
info:
  title: Cheeseria Common Components
  description: Common components for Cheeseria APIs
  version: '2.0.0'
  
components:
  schemas:
    Cheese:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
        url:
          type: string
