spring:
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, \
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, \
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
logging:
  level:
    ROOT: INFO
